import * as fs from "fs";
import * as path from "path";
import * as uuid from "uuid";

import { Service } from "@rsi/core";
import { Cdn } from "@rsi/server";

import { Media } from "./media";
import { Tracks } from "./tracks";

class Medialibrary extends Service {
  constructor() {
    super();
    this.id = "ea65d5eb-d5fb-4ceb-a568-ed24fcf37e20"; // random id
    this.resources.push(new Tracks(this));

    const cnd = Cdn.getInstance();
    cnd.register("images", "RLA6JMJK_normal.jpg", (image: string): Buffer => {
      // rsiLogger.getInstance().getLogger("cdn.callback").log('debug', `Looking for ${image}`);
      let img: Buffer;

      // tslint:disable:max-line-length
      const data =
        "/9j/4AAQSkZJRgABAQAAAQABAAD/4gKgSUNDX1BST0ZJTEUAAQEAAAKQbGNtcwQwAABtbnRyUkdCIFhZWiAH4QACAA8ADgALADlhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWxjbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtkZXNjAAABCAAAADhjcHJ0AAABQAAAAE53dHB0AAABkAAAABRjaGFkAAABpAAAACxyWFlaAAAB0AAAABRiWFlaAAAB5AAAABRnWFlaAAAB+AAAABRyVFJDAAACDAAAACBnVFJDAAACLAAAACBiVFJDAAACTAAAACBjaHJtAAACbAAAACRtbHVjAAAAAAAAAAEAAAAMZW5VUwAAABwAAAAcAHMAUgBHAEIAIABiAHUAaQBsAHQALQBpAG4AAG1sdWMAAAAAAAAAAQAAAAxlblVTAAAAMgAAABwATgBvACAAYwBvAHAAeQByAGkAZwBoAHQALAAgAHUAcwBlACAAZgByAGUAZQBsAHkAAAAAWFlaIAAAAAAAAPbWAAEAAAAA0y1zZjMyAAAAAAABDEoAAAXj///zKgAAB5sAAP2H///7ov///aMAAAPYAADAlFhZWiAAAAAAAABvlAAAOO4AAAOQWFlaIAAAAAAAACSdAAAPgwAAtr5YWVogAAAAAAAAYqUAALeQAAAY3nBhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbcGFyYQAAAAAAAwAAAAJmZgAA8qcAAA1ZAAAT0AAACltwYXJhAAAAAAADAAAAAmZmAADypwAADVkAABPQAAAKW2Nocm0AAAAAAAMAAAAAo9cAAFR7AABMzQAAmZoAACZmAAAPXP/bAEMABQMEBAQDBQQEBAUFBQYHDAgHBwcHDwsLCQwRDxISEQ8RERMWHBcTFBoVEREYIRgaHR0fHx8TFyIkIh4kHB4fHv/bAEMBBQUFBwYHDggIDh4UERQeHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHv/CABEIADAAMAMBIgACEQEDEQH/xAAZAAADAQEBAAAAAAAAAAAAAAAABAUDBgL/xAAYAQEBAQEBAAAAAAAAAAAAAAACAwQFB//aAAwDAQACEAMQAAAB54e353oMoA0Cr4UrKzKdMHQznkVmmvIvDVC3lA3gBpVwRFP/xAAdEAACAwEAAwEAAAAAAAAAAAAEBQECAxMAECAU/9oACAEBAAEFAvoAaxZTSBql+lcC2LZDyKWmnivSZZaeZhDfrGpjbdvjjnLmey9NHZeoIqPXMsa5osj5at9sdJcxxXgE2EKaSLYv0rkWpZ5Niyvr/8QAIxEAAQMCBQUAAAAAAAAAAAAAEwABEQIxEBIhQeEjUYGRwf/aAAgBAwEBPwErEHvgViDVeZzReW+cqkkPmmzd/KpnozfX1rwhMQm+AmITdf/EABoRAAMBAAMAAAAAAAAAAAAAAAARIRABQVH/2gAIAQIBAT8BUeKM46IejixxH//EACgQAAECBgAFBAMAAAAAAAAAAAIBAwAEERITMSIyQVGBBRAUIFJhcf/aAAgBAQAGPwL7AwHXa9khQlEWweGtdr7oE2i2Fw1rpYJhUpb17/uJ+aTnELR8xMq4wj2Nq4RWK/E5pTLhXoUTRPeng3hYuxLXcMOMhjF5q62uokJpecgtLxE/KpzkFw+Im1yYyJqgf2CmFmUbV6UtJfxOJkHPUAczMW5FruGG2TvFlu26m4kJVecQuLzAPh02ndIU5RVsLipTS+6HNqtg8VKbWDfPrpOyff8A/8QAIBAAAgIBBAMBAAAAAAAAAAAAAREAITFBUbHwECBhwf/aAAgBAQABPyH2o4fkDATQ2JlZPkg0NAR2DKAIE2OkYhgG26UKHGwLL+RbkI2TaK3hPClQQtnWwYs4BiwNqpmGQbfpzMEAW/Sh63VwbaR8C0J0h+OOESDgY4LuLOSYoDbqYhkC26cs4fkBCCQ2JHZHkA0NAZWBAcJ+AHv/AP/aAAwDAQACAAMAAAAQIPBVTrgzQ//EAB8RAAICAgMBAQEAAAAAAAAAAAERITEAcUFRYRCB0f/aAAgBAwEBPxArBKM9AUHvjR+XwLT8I81zvBQfqtpJUr+sTebN0UQIdm8nklZuFnP68eFYIRHoiw9cbPwPFKIdAcrfOhn/xAAdEQABBAIDAAAAAAAAAAAAAAARAAEhMRBBUZHB/9oACAECAQE/EDwGgL1PqeTAb4TitR3CPAaP/8QAIBABAAICAgIDAQAAAAAAAAAAAQARIVFxkUGhIDFhgf/aAAgBAQABPxD5PNe5zBZXg9w7cqQwh0L2iynUp1HZCpjGXYPSjBX0gJGL/oePDE5oPrW9kGmiMqa/psi6pw+UAfC/qv1iPBUYEFjRAcVLDZMZEE5pjc0H1Ke2E5sPrWdsKjr6q5wR5inkWZRVjI19GmYjwIBAQKQB4lhO2MiIc0RuaD6lHZBzXqdw2F5PcM9KlModg9Kkt3LdxyUqUzl0X2gS+ZqNwWB4Pfz/AP/ZICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA==";
      // tslint:enable:max-line-length
      // from base64 string
      img = Buffer.from(data, "base64");
      return img;
    });
  }
}

export { Medialibrary, Media, Tracks };
